[package]
name = "recollections"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5"
fs2 = "0.4"
lazy_static = "1.4"
mut_static = "5"
serde_json = "0.9"
